spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pix_transfer_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: false

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      transferAuthorization:
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 1s
  retry:
    instances:
      transferAuthorization:
        maxAttempts: 2
        waitDuration: 5ms
        enableExponentialBackoff: false
  timelimiter:
    instances:
      transferAuthorization:
        timeoutDuration: 250ms
  thread-pool-bulkhead:
    instances:
      transferAuthorization:
        maxThreadPoolSize: 2
        coreThreadPoolSize: 1
        queueCapacity: 1
pix:
  test-setup:
    enabled: true
